"""Added time availability coloumns to Artist

Revision ID: 48921b16097b
Revises: 29533bcb2834
Create Date: 2020-10-09 16:38:39.150386

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48921b16097b'
down_revision = '29533bcb2834'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('time_available_start', sa.DateTime(), nullable=False))
    op.add_column('artist', sa.Column('time_available_stop', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist', 'time_available_stop')
    op.drop_column('artist', 'time_available_start')
    # ### end Alembic commands ###
